services:
  dev:
    build:
      context: ./../
      target: dev
      dockerfile: ./.docker/Dockerfile
    volumes:
      - ./../:/app
    env_file:
      - ./.env
    ports:
      - "3000:3000"
  prod:
    build:
      context: ./../
      target: prod
      dockerfile: ./.docker/Dockerfile
    volumes:
      - ./../:/app
    env_file:
      - ./.env
    ports:
      - "3000:3000"
networks:
    app-network:
        driver: bridge
