name: portfolio
services:
  dev:
    build:
      context: ./../
      target: dev
      dockerfile: ./.docker/Dockerfile
    volumes:
      - ./../public/:/app/public/
      - ./../src/:/app/src/
      - ./../.env:/app/.env
      - ./../next.config.js:/app/next.config.js
      - ./../postcss.config.js:/app/postcss.config.js
      - ./../tailwind.config.js:/app/tailwind.config.js
    env_file:
      - ./../.env
    ports:
      - "3000:3000"
  prod:
    build:
      context: ./../
      target: prod
      dockerfile: ./.docker/Dockerfile
    env_file:
      - ./../.env
    ports:
      - "3000:3000"
