name: Check once a week
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * 1'
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - uses: actions/checkout@v2
      - run: npm install --global npm-check-updates
      - run: ncu