name: Check once a week
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * 1'
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - uses: actions/checkout@v1
      - run: npm install --global npm-check-updates
      - run: ncu
      - if: ${{ steps.check-updates.outcome == 'failure' }}
        run: |
          echo "Hay dependencias desactualizadas."
